# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# https://github.com/craftzdog/solarized-osaka.nvim/blob/main/lua/solarized-osaka/colors.lua
# base04 = "#05151b"       # hsl(192, 100, 5)
# base03 = "#0b282e"       # hsl(192, 100, 11)
# base02 = "#1c373b"       # hsl(192, 81, 14)
# base01 = "#637c88"       # hsl(194, 14, 40)
# base00 = "#728b91"       # hsl(196, 13, 45)
# base0 = "#94b2ba"        # hsl(186, 8, 65)
# base1 = "#a6c2c8"        # hsl(180, 7, 70)
# base2 = "#dfebe3"        # hsl(46, 42, 88)
# base3 = "#f7f4f0"        # hsl(44, 87, 94)
# base4 = "#ffffff"        # hsl(0, 0, 100)
# yellow = "#9a7b1f"       # hsl(45, 100, 35)
# yellow100 = "#ffebc0"    # hsl(47, 100, 80)
# yellow300 = "#ffcc00"    # hsl(45, 100, 50)
# yellow500 = "#9a7b1f"    # hsl(45, 100, 35)
# yellow700 = "#66500d"    # hsl(45, 100, 20)
# yellow900 = "#332b0a"    # hsl(46, 100, 10)
# orange = "#ba6e26"       # hsl(18, 80, 44)
# orange100 = "#ffdcb0"    # hsl(17, 100, 70)
# orange300 = "#ff894f"    # hsl(17, 94, 51)
# orange500 = "#ba6e26"    # hsl(18, 80, 44)
# orange700 = "#914f1e"    # hsl(18, 81, 35)
# orange900 = "#4c2c12"    # hsl(18, 80, 20)
# red = "#d05858"          # hsl(1, 71, 52)
# red100 = "#ffb0b0"       # hsl(1, 100, 80)
# red300 = "#ff5151"       # hsl(1, 90, 64)
# red500 = "#d05858"       # hsl(1, 71, 52)
# red700 = "#914141"       # hsl(1, 71, 42)
# red900 = "#482020"       # hsl(1, 71, 20)
# magenta = "#d946aa"      # hsl(331, 64, 52)
# magenta100 = "#ffb0e9"   # hsl(331, 100, 73)
# magenta300 = "#ff70cf"   # hsl(331, 86, 64)
# magenta500 = "#d946aa"   # hsl(331, 64, 52)
# magenta700 = "#91416d"   # hsl(331, 64, 42)
# magenta900 = "#482035"   # hsl(331, 65, 20)
# violet = "#8c7fff"       # hsl(237, 43, 60)
# violet100 = "#e3dcff"    # hsl(236, 100, 90)
# violet300 = "#c0b3ff"    # hsl(237, 69, 77)
# violet500 = "#8c7fff"    # hsl(237, 43, 60)
# violet700 = "#7263d4"    # hsl(237, 43, 50)
# violet900 = "#3a3167"    # hsl(237, 42, 25)
# blue = "#1d74bb"         # hsl(205, 69, 49)
# blue100 = "#d5eaff"      # hsl(205, 100, 83)
# blue300 = "#6ca4ff"      # hsl(205, 90, 62)
# blue500 = "#1d74bb"      # hsl(205, 69, 49)
# blue700 = "#165694"      # hsl(205, 70, 35)
# blue900 = "#0b2c4a"      # hsl(205, 69, 20)
# cyan = "#1d9f91"         # hsl(175, 59, 40)
# cyan100 = "#e1fff7"      # hsl(176, 100, 86)
# cyan300 = "#4cd9b0"      # hsl(175, 85, 55)
# cyan500 = "#1d9f91"      # hsl(175, 59, 40)
# cyan700 = "#155f55"      # hsl(182, 59, 25)
# cyan900 = "#0b2f2c"      # hsl(183, 58, 15)
# green = "#aad75f"        # hsl(68, 100, 30)
# green100 = "#e6ffd5"     # hsl(90, 100, 84)
# green300 = "#e6ffb0"     # hsl(76, 100, 49)
# green500 = "#aad75f"     # hsl(68, 100, 30)
# green700 = "#668f3a"     # hsl(68, 100, 20)
# green900 = "#33491d"     # hsl(68, 100, 10)


right_format = "$cmd_duration"

[character]
success_symbol = "[➜](bold #859900)"
error_symbol = "[➜](bold #dc322f)"

[cmd_duration]
format = "[ $duration]($style)"
style = "bold #f7f4f0"

[directory]
read_only = " "
style = "bold #268bd2"

[docker_context]
symbol = " "

[git_branch]
symbol = " "
style = "bold #859900"

[git_status]
style = "bold #0b282e"

[java]
symbol = " "
style = "bold #1d74bb"

[nix_shell]
symbol = " "
style = "bold #1d74bb"
impure_msg = " [impure](bold #dc322f)"
pure_msg = " [pure](bold)"

[nodejs]
symbol = " "
style = "bold #9a7b1f"

[package]
style = "bold #dc322f"

[python]
symbol = " "
style = "bold #9a7b1f"

[ruby]
symbol = " "
style = "bold #dc322f"

